apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cks-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - app: cks-backend
                  namespace: default
                  repoURL: https://gitlab.homelabz.eu/homelabz-eu/cks-backend.git
                - app: cks-frontend
                  namespace: default
                  repoURL: https://gitlab.homelabz.eu/homelabz-eu/cks-frontend.git
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: In
                    values: [prod]
  template:
    metadata:
      name: "{{.app}}-{{.name}}"
      labels:
        app: "{{.app}}"
        env: "{{.name}}"
        project: cks
    spec:
      project: default
      source:
        repoURL: "{{.repoURL}}"
        targetRevision: HEAD
        path: "kustomize/overlays/{{.name}}"
      destination:
        server: "{{.server}}"
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
